/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0171417b126879f67a9de6eaa5d9ef80)
interface __BaseEnv_Env {
	IMAGE_BUCKET: R2Bucket;
	DB: D1Database;
	IMAGES: ImagesBinding;
	AI_GATEWAY_URL: "https://gateway.ai.cloudflare.com/v1/4e7d0e9ce74b7a6ea034ccedc67ead45/chikachow/openrouter/v1/chat/completions";
	CLERK_OAUTH_ISSUER: "https://advanced-mullet-11.clerk.accounts.dev";
	CLERK_PUBLISHABLE_KEY: string;
	CLERK_SECRET_KEY: string;
	BOTTLE_CAPTURE_WORKFLOW: Workflow<Parameters<import("./worker/index").BottleCaptureWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_GATEWAY_URL" | "CLERK_OAUTH_ISSUER" | "CLERK_PUBLISHABLE_KEY" | "CLERK_SECRET_KEY">> {}
}
