name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  format:
    uses: ./.github/workflows/ci-format.yml
    secrets: inherit

  lint:
    uses: ./.github/workflows/ci-lint.yml
    secrets: inherit

  typecheck:
    uses: ./.github/workflows/ci-typecheck.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/ci-test.yml
    secrets: inherit

  build:
    uses: ./.github/workflows/ci-build.yml
    secrets: inherit

  ci:
    name: ci
    runs-on: ubuntu-latest
    needs:
      - format
      - lint
      - typecheck
      - test
      - build
    if: ${{ always() }}
    steps:
      - name: Require all CI jobs to pass
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            exit 1
          fi

          if [[ "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            exit 1
          fi

          if [[ "${{ contains(needs.*.result, 'skipped') }}" == "true" ]]; then
            exit 1
          fi
